"""intial migration, creating tables

Revision ID: 2eb8e42e8d81
Revises: 
Create Date: 2026-01-14 13:56:00.218738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eb8e42e8d81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', postgresql.ENUM('idee', 'achete', 'commande', 'en_cours_livraison', 'livre', 'recupere', 'emballe', 'offert', name='gift_status'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 9', name='ck_gifts_price'),
    sa.CheckConstraint('quantity >= 1', name='ck_gifts_quantity'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_gifts_status', 'gifts', ['status'], unique=False)
    op.create_index('idx_gifts_user', 'gifts', ['user_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_groups_user', 'groups', ['user_id'], unique=False)
    op.create_table('recipients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipients_name', 'recipients', ['name'], unique=False)
    op.create_index('idx_recipients_user', 'recipients', ['user_id'], unique=False)
    op.create_table('gift_recipients',
    sa.Column('gift_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gift_id'], ['gifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gift_id', 'recipient_id')
    )
    op.create_index('idx_gift_recipients_recipient', 'gift_recipients', ['recipient_id'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'recipient_id')
    )
    op.create_index('idx_group_members_recipient', 'group_members', ['recipient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_group_members_recipient', table_name='group_members')
    op.drop_table('group_members')
    op.drop_index('idx_gift_recipients_recipient', table_name='gift_recipients')
    op.drop_table('gift_recipients')
    op.drop_index('idx_recipients_user', table_name='recipients')
    op.drop_index('idx_recipients_name', table_name='recipients')
    op.drop_table('recipients')
    op.drop_index('idx_groups_user', table_name='groups')
    op.drop_table('groups')
    op.drop_index('idx_gifts_user', table_name='gifts')
    op.drop_index('idx_gifts_status', table_name='gifts')
    op.drop_table('gifts')
    op.drop_table('users')
    # ### end Alembic commands ###
