"""Adding refresh token fingerprint field

Revision ID: 3f0a16adc692
Revises: dc3c972ef225
Create Date: 2026-01-19 22:01:49.883147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0a16adc692'
down_revision: Union[str, Sequence[str], None] = 'dc3c972ef225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('token_fingerprint', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_refresh_tokens_token_fingerprint'), 'refresh_tokens', ['token_fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_token_fingerprint'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'token_fingerprint')
    # ### end Alembic commands ###
