"""Fixing wrong price constraint on gifts table.

Revision ID: 668b0bb62cf3
Revises: e612bf1c261c
Create Date: 2026-02-14 01:38:47.713962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668b0bb62cf3'
down_revision: Union[str, Sequence[str], None] = 'e612bf1c261c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_gifts_price', 'gifts', type_='check')
    op.create_check_constraint('ck_gifts_price', 'gifts', 'price >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_gifts_price', 'gifts', type_='check')
    op.create_check_constraint('ck_gifts_price', 'gifts', 'price >= 9')
    # ### end Alembic commands ###
