"""adding_email_verification_to_users

Revision ID: ac1cd9abb48b
Revises: 668b0bb62cf3
Create Date: 2026-02-15 01:18:44.350347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1cd9abb48b'
down_revision: Union[str, Sequence[str], None] = '668b0bb62cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    
    op.execute("UPDATE users SET is_verified = true WHERE is_verified IS NULL")
    
    op.alter_column('users', 'is_verified', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token_expires_at')
    op.drop_column('users', 'verification_token_hash')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
