"""adding verification_token_fingerprint to users

Revision ID: d53d26fba49d
Revises: ac1cd9abb48b
Create Date: 2026-02-26 15:31:39.790776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53d26fba49d'
down_revision: Union[str, Sequence[str], None] = 'ac1cd9abb48b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token_fingerprint', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_verification_token_fingerprint'), 'users', ['verification_token_fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_verification_token_fingerprint'), table_name='users')
    op.drop_column('users', 'verification_token_fingerprint')
    # ### end Alembic commands ###
