"""adding budget column to users table

Revision ID: e612bf1c261c
Revises: b7bd6230427d
Create Date: 2026-02-14 01:25:44.959248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e612bf1c261c'
down_revision: Union[str, Sequence[str], None] = 'b7bd6230427d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_check_constraint('ck_users_budget_positive', 'users', 'budget > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_budget_positive', 'users', type_='check')
    op.drop_column('users', 'budget')
    # ### end Alembic commands ###
