FROM python:3.12-slim

WORKDIR /code

# Copie des fichiers de configuration
COPY requirements-prod.txt .

# Installation des dépendances
RUN pip install --no-cache-dir --upgrade -r requirements-prod.txt

# Copie du code source
COPY src/ ./src/

# Exposition du port
EXPOSE 8000

# Commande de démarrage avec uvicorn (recommandé pour la production)
CMD ["fastapi", "prod", "src/main.py", "--host", "0.0.0.0", "--port", "8000"]
