FROM python:3.14-slim-bookworm

WORKDIR /app

# Copy requirements
COPY requirements-prod.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r requirements-prod.txt

# Copy source code
COPY . .

# Expose port
EXPOSE 8000

# Command to run the app
CMD ["fastapi", "run", "src/main.py"]
