FROM python:3.12-slim

WORKDIR /code

# Copy requirements
COPY requirements-prod.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r requirements-prod.txt

# Copy source code
COPY src/ ./src/

# Expose port
EXPOSE 8000

# Command to run the app
CMD ["fastapi", "prod", "src/main.py"]
